version: '3.5'
services:
  test_jooq:
    image: postgres:14
    container_name: test_jooq
    restart: unless-stopped
    ports:
      - "6002:5432"
    environment:
      POSTGRES_DB: test_jooq
      POSTGRES_USER: surgerate
      POSTGRES_PASSWORD: 123456
    networks:
      - shop-network

# Services on the same network can communicate with each other.
networks:
  shop-network:
    driver: bridge
